version: "3.8"

services:
  db:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
    networks:
      - mynetwork

  api:
    build:
      context: .
      dockerfile: Dockerfiles/php.dockerfile
    volumes:
      - ./api:/var/www/html:delegated
    ports:
      - '8000:9000' # Expose port 9000 inside the container to port 8000 on the host
    networks:
      - mynetwork

  client:
    build:
      context: .
      dockerfile: Dockerfiles/nuxt.dockerfile
    ports:
      - '3000:3000'
    networks:
      - mynetwork

  nginx:
  build:
    context: .
    dockerfile: Dockerfiles/nginx.dockerfile
  ports:
    - '80:80'
    - '443:443'
  volumes:
    - ./api:/var/www/html
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - ./certs:/etc/nginx/certs
  depends_on:
    - api
    - db
  networks:
    - mynetwork

networks:
  mynetwork:
    driver: bridge
